### ISSUE TITLE
Kick message when forced-online-auth is enabled should be more clear

### ISSUE THREAD

**Issue by Londiuh** [Additional-Mods/simplerauth#34] opened 2021-08-10 19:50 UTC
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
The kick message when `forced-online-auth` is enabled, and you join with a premium account name, should be changed to be more clear. Many players don't know what `invalid sesion` means, or they think that the server is premium.

**Describe alternatives you've considered**
The message should say, _**"You're joining with a premium username, and you're non-premium. Choose another name to play."**_ or something like that

**Additional context**
![image](https://user-images.githubusercontent.com/22352246/128923842-9be38b5c-4333-4be9-a2f9-f01774d3689d.png)

**Version**
Mod version: 1.3.0
Minecraft version: 1.17.1
Fabric version: 0.7.4

**Comment by Dqu1J** [comment] 2021-08-10 19:57
Duplicate of #29

**Closed as completed by Dqu1J** 2021-08-10 19:57 UTC
Labels: enhancement, invalid
